// default package
// Generated 26/07/2016 9:26:55 AM by Hibernate Tools 5.1.0.Beta1
package com.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Register generated by hbm2java
 */
@Entity
@Table(name = "register", catalog = "stp")
public class Register implements java.io.Serializable {

	private String email;
	private String password;
	private String firstname;
	private String lastname;
	private Integer phonenumber;
	private String resettoken;

	public Register() {
	}

	public Register(String email) {
		this.email = email;
	}

	public Register(String email, String password, String firstname, String lastname, Integer phonenumber,
			String resettoken) {
		this.email = email;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.phonenumber = phonenumber;
		this.resettoken = resettoken;
	}

	@Id

	@Column(name = "email", unique = true, nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "firstname", length = 45)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 45)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "phonenumber")
	public Integer getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(Integer phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Column(name = "resettoken", length = 45)
	public String getResettoken() {
		return this.resettoken;
	}

	public void setResettoken(String resettoken) {
		this.resettoken = resettoken;
	}

}
