// default package
// Generated 19/07/2016 2:36:11 PM by Hibernate Tools 5.1.0.Beta1

package com.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Session generated by hbm2java
 */
@Entity
@Table(name = "session", catalog = "stp")
public class Session implements java.io.Serializable {

	private String email;
	private byte[] token;

	public Session() {
	}

	public Session(String email) {
		this.email = email;
	}

	public Session(String email, byte[] token) {
		this.email = email;
		this.token = token;
	}

	@Id

	@Column(name = "email", unique = true, nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "token")
	public byte[] getToken() {
		return this.token;
	}

	public void setToken(byte[] token) {
		this.token = token;
	}

}
