// default package
// Generated 18/07/2016 3:58:07 PM by Hibernate Tools 5.1.0.Beta1

package com.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserId generated by hbm2java
 */
@Embeddable
public class UserId implements java.io.Serializable {

	private String name;
	private Integer one;
	private Integer two;

	public UserId() {
	}

	public UserId(String name, Integer one, Integer two) {
		this.name = name;
		this.one = one;
		this.two = two;
	}

	@Column(name = "name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "one")
	public Integer getOne() {
		return this.one;
	}

	public void setOne(Integer one) {
		this.one = one;
	}

	@Column(name = "two")
	public Integer getTwo() {
		return this.two;
	}

	public void setTwo(Integer two) {
		this.two = two;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserId))
			return false;
		UserId castOther = (UserId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
				&& this.getName().equals(castOther.getName())))
				&& ((this.getOne() == castOther.getOne()) || (this.getOne() != null && castOther.getOne() != null
						&& this.getOne().equals(castOther.getOne())))
				&& ((this.getTwo() == castOther.getTwo()) || (this.getTwo() != null && castOther.getTwo() != null
						&& this.getTwo().equals(castOther.getTwo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getOne() == null ? 0 : this.getOne().hashCode());
		result = 37 * result + (getTwo() == null ? 0 : this.getTwo().hashCode());
		return result;
	}

}
