// default package
// Generated 18/07/2016 3:58:07 PM by Hibernate Tools 5.1.0.Beta1
package com.entity;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "stp")
public class User implements java.io.Serializable {

	private UserId id;

	public User() {
	}

	public User(UserId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "name", column = @Column(name = "name", length = 30)),
			@AttributeOverride(name = "one", column = @Column(name = "one")),
			@AttributeOverride(name = "two", column = @Column(name = "two")) })
	public UserId getId() {
		return this.id;
	}

	public void setId(UserId id) {
		this.id = id;
	}

}
